---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-service
  labels:
    name: account-service
  namespace: my-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: account-service
    spec:
      containers:
      - name: account-service
        image: sangdongvan/account-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
      nodeSelector:
        beta.kubernetes.io/os: linux