---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    name: account-service
  namespace: my-store
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    name: account-service