---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    name: config-service
  namespace: my-store
spec:
  ports:
    # the port that this service should serve on
  - port: 8888
    targetPort: 8888
  selector:
    name: config-service