---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: online-store-web
  labels:
    name: online-store-web
  namespace: my-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: online-store-web
    spec:
      containers:
      - name: online-store-web
        image: sangdongvan/online-store-web:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8787
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        livenessProbe:
          httpGet:
            path: /
            port: 8787
          initialDelaySeconds: 1200
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8787
          initialDelaySeconds: 120
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
