---
apiVersion: v1
kind: Service
metadata:
  name: online-store-web
  labels:
    name: online-store-web
  namespace: my-store
spec:
  type: NodePort
  ports:
  - port: 8787
    targetPort: 8787
    nodePort: 31603
  selector:
    name: online-store-web