---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
  labels:
    name: user-service
  namespace: my-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user-service
    spec:
      containers:
      - name: user-service
        image: sangdongvan/user-service:0.0.1-SNAPSHOT
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8181
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8181
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8181
          initialDelaySeconds: 180
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
