---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
  labels:
    name: user-service
  namespace: my-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user-service
    spec:
      containers:
      - name: user-service
        image: sangdongvan/user-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 18027
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
      nodeSelector:
        beta.kubernetes.io/os: linux
