---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: user-service
  namespace: my-store
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 18027
  selector:
    name: user
