spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
server:
  port: 18028
---
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:17023/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:17023/test?useSSL=false
    username: root
    password: dbpass
    initialize: false
  jpa:
    hibernate:
      ddl-auto: create
