spring:
  profiles: kubernetes
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service/eureka/