server:
  port: 80
spring:
  cloud:
    consul:
      host: consul
security:
  oauth2:
    resource:
      userInfoUri: http://user-service/uaa/user
    client:
      accessTokenUri: http://user-service/uaa/oauth/token
      userAuthorizationUri: http://auth.learnmicroservices.org/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
