spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
server:
  port: 18021
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: localhost
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:18020
    auth-service:
      path: /user/**
      url: http://localhost:18027/uaa/user
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      accessTokenUri: http://localhost:18027/uaa/oauth/token
      userAuthorizationUri: http://localhost:18027/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
