spring:
  profiles:
    active: default,localhost
---
server:
  port: 8031
spring:
  profiles: default
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
zuul:
  ignored-services: '*'
  routes:
    edge-service: /api/**
security:
  enable-csrf: false
  ignored: /assets/**
management:
  security:
    enabled: false
---
spring:
  profiles: localhost
zuul:
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:8032
    auth-service:
      path: /user/**
      url: http://localhost:8033/uaa/user
security:
  oauth2:
    resource:
      userInfoUri: http://auth.local:8033/uaa/user
    client:
      accessTokenUri: http://auth.local:8033/uaa/oauth/token
      userAuthorizationUri: http://auth.local:8033/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
---
server:
  port: 80
spring:
  profiles: docker-compose
  cloud:
    consul:
      host: consul
zuul:
  routes:
    edge-service:
      path: /api/**
      url: http://172.33.1.1:8032
    auth-service:
      path: /user/**
      url: http://172.33.1.1:8033/uaa/user
security:
  oauth2:
    resource:
      userInfoUri: http://auth.local:8033/uaa/user
    client:
      accessTokenUri: http://auth.local:8033/uaa/oauth/token
      userAuthorizationUri: http://auth.local:8033/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
