---
spring:
  profiles: kubernetes
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://edge-service:9999
    auth-service:
      path: /user/**
      url: http://159.89.211.108:31604/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://159.89.211.108:31604/uaa/user
    client:
      accessTokenUri: http://159.89.211.108:31604/uaa/oauth/token
      userAuthorizationUri: http://159.89.211.108:31604/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
