apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: shopping-cart-service
    version: v1
  name: shopping-cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart-service
      version: v1
  template:
    metadata:
      labels:
        app: shopping-cart-service
        version: v1
    spec:
      containers:
        - name: shopping-cart-service
          image: sangdongvan/istio-sample-shopping-cart-service:0.1.5-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 18024
              name: http
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
          env:
            - name: JAVA_OPTIONS
              value: -Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
            - name: SPRING_PROFILES_ACTIVE
              value: default,cloud
          livenessProbe:
            httpGet:
              path: /health
              port: 18024
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 18024
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false
