apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  labels:
    app: shopping-cart-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 18024
  selector:
    app: shopping-cart-service
