apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 18022
  selector:
    app: account-service
