---
spring:
  profiles: kubernetes
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user-service: /user/**
    account-service: /account/**
security:
  oauth2:
    resource:
      userInfoUri: http://159.89.211.108:31604/uaa/user
  ignored: /catalog/**
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000