spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
server:
  port: 18020
---
spring:
  profiles: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  ignored-services: "*"
  ignoredPatterns: /**/api/**
  routes:
    account-service: /account/**
    payment-service: /payment/**
    inventory-service: /inventory/**
    order-service: /order/**
    user-service: /user/**
    catalog-service: /catalog/**
    shopping-cart-service: /shoppingcart/**
