spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
server:
  port: 18020
---
spring:
  profiles: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  ignored-services: "*"
  ignoredPatterns: /**/api/**
  routes:
    account-service:
      path: /account/**
      url: http://localhost:18022
    payment-service:
      path: /payment/**
      url: http://localhost:18026
    inventory-service:
      path: /inventory/**
      url: http://localhost:18023
    order-service:
      path: /order/**
      url: http://localhost:18025
    user-service:
      path: /user/**
      url: http://localhost:18027
    catalog-service:
      path: /catalog/**
      url: http://localhost:18028
    shopping-cart-service:
      path: /shoppingcart/**
      url: http://localhost:18024
