apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    name: neo4j
spec:
  ports:
    # the port that this service should serve on
  - port: 7474
    targetPort: 7474
  selector:
    name: neo4j
