spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  datasource:
    database: mysql
server:
  port: 18026
---
spring:
  profiles: localhost
  redis:
    host: localhost
    port: 17024
  datasource:
    url: jdbc:mysql://localhost:17023/dev?useSSL=false
    username: root
    password: dbpass
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 17024
  datasource:
    url: jdbc:mysql://localhost:17023/test?useSSL=false
    username: root
    password: dbpass
