spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  cache:
    type: redis
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
server:
  port: 18026
---
spring:
  profiles: localhost
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:17023/dev?useSSL=false
    username: root
    password: dbpass
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:17023/test?useSSL=false
    username: root
    password: dbpass
