apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: inventory-service
    version: v1
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
      version: v1
  template:
    metadata:
      labels:
        app: inventory-service
        version: v1
    spec:
      containers:
        - name: inventory-service
          image: sangdongvan/istio-sample-inventory-service:0.1.6-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 18023
              name: http
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
          env:
            - name: JAVA_OPTIONS
              value: -Xms512m -Xmx1024m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
            - name: SPRING_PROFILES_ACTIVE
              value: default,cloud
          livenessProbe:
            httpGet:
              path: /health
              port: 18023
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 18023
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false
