apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 18023
  selector:
    app: inventory-service
