spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
server:
  port: 18027
  servlet:
    context-path: /uaa
management:
  server:
    port: 38027
---
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:17023/dev
    username: root
    password: dbpass
    initialization-mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
#logging.level.org.springframework.security: DEBUG
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:17023/test
    username: root
    password: dbpass
  jpa:
    hibernate:
      ddl-auto: create
