management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
spring:
  datasource:
    url: jdbc:mysql://mysql/dev
    username: root
    password: dbpass
    initialization-mode: always
