spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
server:
  port: 18027
  context-path: /uaa
security:
  user:
    password: password
  enable-csrf: false
  ignored: /resources/**
management:
  security:
    enabled: false
  port: 38027
---
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:17023/dev
    username: root
    password: dbpass
    initialize: true
logging.level.org.springframework.security: DEBUG
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:17023/test
    username: root
    password: dbpass
    initialize: false
