spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
server:
  port: 18027
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:17023/dev
    username: root
    password: dbpass
logging.level.org.springframework.security: DEBUG
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:17023/test
    username: root
    password: dbpass
  jpa:
    hibernate:
      ddl-auto: create
