spring:
  profiles:
    active: default,localhost
---
server:
  port: 8033
  contextPath: /uaa
spring:
  profiles: default
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: ${server.contextPath}/health
security:
  user:
    password: password
  enable-csrf: false
  ignored: /resources/**
management:
  security:
    enabled: false
---
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:17023/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
logging.level.org.springframework.security: DEBUG
---
server:
  port: 80
spring:
  profiles: docker-compose
  cloud:
    consul:
      host: consul
  zipkin:
    base-url: http://zipkin:9411/
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:17023/test
    username: root
    password: dbpass
    initialize: false
