---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: mongo
  namespace: my-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:2.3
        ports:
        - name: mongo
          containerPort: 27017
      nodeSelector:
        beta.kubernetes.io/os: linux