---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neo4j
  labels:
    name: neo4j
  namespace: my-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:2.3
        env:
        - name: NEO4J_AUTH
          value: none
        ports:
        - name: neo4j
          containerPort: 7474
      nodeSelector:
        beta.kubernetes.io/os: linux