---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
  namespace: my-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:3.0
        ports:
        - name: redis
          containerPort: 6379
      nodeSelector:
        beta.kubernetes.io/os: linux