apiVersion: v1
kind: Service
metadata:
  name: online-store-web
  labels:
    app: online-store-web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 18021
  selector:
    app: online-store-web
