spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
server:
  port: 18025
management:
  security:
    enabled: false
---
spring:
  profiles: localhost
  data:
    mongodb:
      host: localhost
      port: 17022
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      client-id: acme
---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 17022
