spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
server:
  port: 18025
---
spring:
  profiles: localhost
  data:
    mongodb:
      uri: mongodb://user:pwd@localhost:17022/orders
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      client-id: acme
#  ignored: /api/**
---
spring:
  profiles: test
  data:
    mongodb:
      uri: mongodb://user:pwd@localhost:17022/test-orders
