spring:
  profiles:
    active: default,localhost
---
server:
  port: 0
spring:
  profiles: default
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
management:
  security:
    enabled: false
---
spring:
  profiles: localhost
  data:
    mongodb:
      host: localhost
      port: 17022
security:
  oauth2:
    resource:
      userInfoUri: http://auth.local:8033/uaa/user
    client:
      client-id: acme
---
spring:
  profiles: docker-compose
  cloud:
    consul:
      host: consul
  data:
    mongodb:
      host: mongo
      port: 27017
security:
  oauth2:
    resource:
      userInfoUri: http://auth.local:8033/uaa/user
    client:
      client-id: acme
---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 17022
