spring:
  profiles:
    active: default,localhost
---
server:
  port: 0
spring:
  profiles: default
---
spring:
  profiles: localhost
  neo4j:
    host: localhost
    port: 17021
---
server:
  port: 80
spring:
  profiles: docker-compose
  zipkin:
    base-url: http://zipkin:9411/
  neo4j:
    host: neo4j
    port: 7474
---
spring:
  profiles: test
  neo4j:
    host: localhost
    port: 17021
