spring:
  profiles:
    active: default,localhost
server:
  port: 18023
---
spring:
  profiles: default
---
spring:
  profiles: localhost
  data:
    neo4j:
      uri: bolt://localhost:17021
---
spring:
  profiles: test
  data:
    neo4j:
      uri: bolt://localhost:17021
