spring:
  profiles:
    active: default,localhost
server:
  port: 18023
---
spring:
  profiles: default
---
spring:
  profiles: localhost
  neo4j:
    host: localhost
    port: 17021
---
spring:
  profiles: test
  neo4j:
    host: localhost
    port: 17021
