---
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
spring:
  datasource:
    url: jdbc:mysql://mysql/dev
    username: root
    password: dbpass
security:
  oauth2:
    resource:
      userInfoUri: http://auth.learnmicroservices.org/uaa/user
    client:
      client-id: acme
