---
spring:
  datasource:
    url: jdbc:mysql://mysql/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
security:
  oauth2:
    resource:
      userInfoUri: http://auth.learnmicroservices.org/uaa/user
    client:
      client-id: acme
      access-token-uri: http://auth.learnmicroservices.org
