spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
server:
  port: 18022
---
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:17023/dev?useSSL=false
    username: root
    password: dbpass
management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      clientId: acme
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:17023/test?useSSL=false
    username: root
    password: dbpass
  jpa:
    hibernate:
      ddl-auto: create
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      clientId: acme
