spring:
  profiles: kubernetes
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
server:
  port: 8080
security:
  oauth2:
    resource:
      userInfoUri: http://159.89.211.108:31604/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service/eureka/