spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
server:
  port: 18024
---
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:17023/dev?useSSL=false
    username: root
    password: dbpass
    initialization-mode: always
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      accessTokenUri: http://localhost:18027/uaa/oauth/token
      userAuthorizationUri: http://localhost:18027/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
#  enable-csrf: false
#  ignored: /api/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:17023/test
    username: root
    password: dbpass
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      accessTokenUri: http://localhost:18027/uaa/oauth/token
      userAuthorizationUri: http://localhost:18027/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
