server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
security:
  oauth2:
    resource:
      userInfoUri: http://user-service/uaa/user
    client:
      clientId: acme
