spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
security:
  oauth2:
    resource:
      userInfoUri: http://auth.learnmicroservices.org/uaa/user
    client:
      accessTokenUri: http://auth.learnmicroservices.org/uaa/oauth/token
      userAuthorizationUri: http://auth.learnmicroservices.org/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
