spring:
  profiles:
    active: default,localhost
---
spring:
  profiles: default
server:
  port: 18024
---
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://localhost:17023/dev
    username: root
    password: dbpass
    platform: mysql
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
#  enable-csrf: false
#  ignored: /api/**
---
spring:
  application:
    name: account-service
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:17023/test
    username: root
    password: dbpass
    platform: mysql
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:18027/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
