docker push sangdongvan/istio-sample-online-store-web:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-catalog-service:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-payment-service:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-edge-service:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-online-store-web:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-user-service:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-account-service:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-order-service:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-inventory-service:0.1.6-SNAPSHOT
docker push sangdongvan/istio-sample-shopping-cart-service:0.1.6-SNAPSHOT
